### ISSUE TITLE
Pixhawk 4 - GPS, Safety switch and buzzer connection problems problem

### ISSUE THREAD

**Issue by FeCLN** [pixhawk/Hardware#106]
Hello, I am from Skyrats, a Brazilian autonomous drone team. Recently we bought a Pixhawk 4 with the intention of using it with some other components in the GPS port, along with the GPS of course. These components are: a normal safety switch, a buzzer, and a SE100 GPS (All of them tested in a Pixhawk 1 and working normally). After making some wiring connections; all of them accordingly to each datasheet and pinout, we tried to use it in a Pixhawk 4, but unfortunately we didn't have good results. The safety switch didn't work, the LED didn't light up, and checking with a voltmeter we didn't even get any signal from these ports. The buzzer makes a sound, but it's completely inaudible. And the worst part is, the GPS didn't work, in QGroundControl we receive only a "0 satellites found with 0 signal strength". Has anyone had this problem? What can we do?

**Comment by hamishwillee** [comment]
Hi @FeCLN,
I'm going to close this because it is not a good place to ask this question. This is an area for the Pixhawk design, so you'd post an issue here if you had an issue with the Pixhawk specification, not with specific hardware.

The best place for this question would be the PX4 discuss server or Slack. That way you will get many more people seeing your question: See http://docs.px4.io/master/en/#getting-help
